---
new_page_extension: md
auto_deploy: false
admin_path: ''
webhook_url: 
sections:
- type: document
  path: src/content/order.md
  label: Order
- type: document
  path: src/content/menudata.json
  label: Menu
- type: document
  path: src/content/sitedata.json
  label: Noemi Site Data
- type: directory
  path: src/content/blog
  label: Blog
  create: all
  match: "**/*"
- type: directory
  path: src/content/pages
  label: Pages
  create: all
  match: "**/*"
  new_doc_ext: md
upload_dir: ''
public_path: " https://res.cloudinary.com/matenoemi"
front_matter_path: ''
use_front_matter_path: true
file_template: ":filename:"
build:
  install_dependencies_command: npm install
  preview_docker_image: node:10
  mount_path: "/srv"
  working_dir: "/srv"
  instant_preview_command: npm run forestry:preview
